services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_files:
      - .env.development
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    env_files:
      - .env.development

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_files:
      - .env.development
    depends_on:
      - mongodb

volumes:
  mongodb_data:
